#!/usr/bin/env bash
# -------------------------------------------------------------------------
# Copyright (c) 1999-2010
# Maryland DSPCAD Research Group, The University of Maryland at College Park

# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.

# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
# -------------------------------------------------------------------------

# Script to run this test
# Usage: runtest [no arguments]
UXLIB=../../bin
echo $1
if [ -f out1.txt ]; then
    rm -r out1.txt
fi

vsim -c -L $UXLIB -lic_plus -quiet -novopt -do util/simulate-do fir fir_testbench
#vsim -c -L $UXLIB -lic_plus -quiet -novopt -do util/simulate-do dotproduct sample_cla_testbench
#vsim -c -L $UXLIB -lic_plus -quiet -novopt -do util/simulate-do myLibs test_mult
#cat out_temp.txt 2> expected-error.txt